name: CI
on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          cargo run --example rob
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          cargo run --example rob
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - name: build
        shell: cmd
        run: |
          cargo run --example rob
